export const COMPANY_REPOSITORY_TOKEN: unique symbol = Symbol("COMPANY_REPOSITORY_TOKEN");
export const COMPANY_CREATE_COMPANY_USE_CASE_TOKEN: unique symbol = Symbol("COMPANY_CREATE_COMPANY_USE_CASE_TOKEN");
