export const EXAMPLE_REPOSITORY_TOKEN: unique symbol = Symbol("EXAMPLE_REPOSITORY_TOKEN");
export const EXAMPLE_CREATE_EXAMPLE_USE_CASE_TOKEN: unique symbol = Symbol("EXAMPLE_CREATE_EXAMPLE_USE_CASE_TOKEN");
export const EXAMPLE_GET_EXAMPLE_USE_CASE_TOKEN: unique symbol = Symbol("EXAMPLE_GET_EXAMPLE_USE_CASE_TOKEN");
